### PR TITLE
update kde platform runtime to 22.08

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
I'm basically going through all of my flatpaks and finding whichever ones haven't updated their runtimes and updating them for you guys (the community) at this point...
anyways, I'll let the flathub bot build this and then test it out once its done

### CODE REVIEW

**Comment by Etaash-mathamsetty** [comment]
bot, build org.polymc.PolyMC

**Comment by Etaash-mathamsetty** [comment]
seems like like I overlooked the publish delay thing, I will come back in another like 20 minutes and try this again

**Comment by Etaash-mathamsetty** [comment]
bot, build org.polymc.PolyMC

**Comment by Etaash-mathamsetty** [comment]
I guess I have to wait an hour after the previous build?

**Comment by Etaash-mathamsetty** [comment]
RIP PolyMC, lenny did the unexpected

**Comment by dada513** [comment]
PR this to Prism launcher flatpak

**Comment by Etaash-mathamsetty** [comment]
> PR this to Prism launcher flatpak

Their flatpak runtime has already been updated

**Pull request closed without merging**
