### PR TITLE
QT6 initial support

### PR DESCRIPTION
**Pull request by dada513**

### CODE REVIEW

**Comment by dada513** [comment]
requires https://github.com/flathub/flathub/pull/3012 or something else because qt5 compat is missing

**Comment by hfiguiere** [comment]
> requires [flathub/flathub#3012](https://github.com/flathub/flathub/pull/3012) or something else because qt5 compat is missing

not it doesn't need that. This is something else that doesn't do what you think it does.

if you need qt5 compat, you have to build it.

**Comment by DioEgizio** [comment]
Well that sucks. Why does the kde runtime not provide it

**Comment by hfiguiere** [comment]
https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/26

**Comment by dada513** [comment]
> [invent.kde.org/packaging/flatpak-kde-runtime/-/issues/26](https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/26)

yeah I saw that old issue with no responses

**Comment by dada513** [comment]
anyways this kinda works:
```
  - name: qt5compat
    buildsystem: cmake-ninja
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    sources:
      - type: archive
        url: https://download.qt.io/archive/qt/6.3/6.3.1/submodules/qt5compat-everywhere-src-6.3.1.tar.xz
        sha256: a43ec62bd778eaecf88ad7847118d1c2a471b0fcb820f93beb311d7ab9566cfd
```

compiles, but then doesn't find it at runtime

**Comment by guihkx** [comment]
> compiles, but then doesn't find it at runtime

Try to create a symbolic link of the qt5compat library to `/app/libs`, something like this:

https://github.com/flathub/com.github.rssguard/blob/fa2cdff09f63663b6bf7c6a57628d46affafdbb3/com.github.rssguard.yaml#L25-L40

**Comment by dada513** [comment]
> > compiles, but then doesn't find it at runtime
> 
> Try to create a symbolic link of the qt5compat library to `/app/libs`, something like this:
> 
> [flathub/com.github.rssguard@`fa2cdff`/com.github.rssguard.yaml#L25-L40](https://github.com/flathub/com.github.rssguard/blob/fa2cdff09f63663b6bf7c6a57628d46affafdbb3/com.github.rssguard.yaml#L25-L40)

Worked great, thanks

**Comment by dada513** [comment]
pushed this to beta

**Pull request closed without merging**
